# Generated by Django 3.1 on 2020-08-31 05:07

from django.db import migrations

def create_data(apps, schema_editor):
    # Get Employee Model Object from employees from INSTALLED_APPS
    Employee = apps.get_model('employees', 'Employee')
    # Dummy Data is added so that Database isn't empty when API starts
    Employee(eid="EMP001", ename="Washington", email="wton13@email.com", phone="1234567890").save()

class Migration(migrations.Migration):
    # dependencies property relates other files to be considered during migration process
    dependencies = [
        ('employees', '0001_initial'),
    ]

    # Operations to be performed when Migrations are triggered
    # Here create_data method will be called when Migrations are triggered
    operations = [
        migrations.RunPython(create_data)
    ]
